### ISSUE TITLE
feat: filter words

### ISSUE THREAD

**Issue by jefo3** [jefo3/BotRT#5]
add filtro de palavras para evitar que o bot realize o RT e Like em post relacionados com onlyfans ou que tenha alguma '#' com o bot em execução percebi como os conteudos relacionados a NSFW

**Comment by ericrodriguesfer** [comment]
"add filtro"... escreva a issue em somente um idioma, ou é inglês ou é português. Escolha.

**Comment by jefo3** [comment]
opa, obrigado, anotado, vou seguir um padrão na proxima
